# Generated by Django 5.1.2 on 2024-10-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_usermodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='from_country',
            field=models.CharField(max_length=150),
        ),
    ]
