# Generated by Django 5.1.2 on 2024-10-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_usermodel_country_alter_usermodel_from_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
